import { db } from "./db";

export interface DeadlineInput {
  sourceModule: string;
  sourceId: string;
  title: string;
  category: string;
  date: Date;
  documentId?: string | null;
  relatedPersonId?: string | null;
  relatedClientId?: string | null;
  relatedVendor?: string | null;
  notes?: string | null;
}

export function computeDeadlineStatus(date: Date, currentStatus?: string): string {
  if (currentStatus === "COMPLETED" || currentStatus === "CANCELLED") return currentStatus;
  const now = new Date();
  const days = (date.getTime() - now.getTime()) / (1000 * 60 * 60 * 24);
  if (days < 0) return "OVERDUE";
  if (days <= 14) return "DUE_SOON";
  return "UPCOMING";
}

/**
 * Create or refresh an auto-generated deadline tied to a source record.
 * Keyed on (sourceModule, sourceId, category) so re-saving a record (e.g.
 * editing a due date) updates the same deadline instead of duplicating it.
 * Never resurrects a deadline the user already completed/cancelled.
 */
export async function upsertAutoDeadline(input: DeadlineInput) {
  const existing = await db.deadline.findFirst({
    where: {
      sourceModule: input.sourceModule,
      sourceId: input.sourceId,
      category: input.category,
      autoGenerated: true,
    },
  });

  const status = computeDeadlineStatus(input.date, existing?.status);

  if (existing) {
    return db.deadline.update({
      where: { id: existing.id },
      data: {
        title: input.title,
        date: input.date,
        documentId: input.documentId ?? existing.documentId,
        relatedPersonId: input.relatedPersonId ?? existing.relatedPersonId,
        relatedClientId: input.relatedClientId ?? existing.relatedClientId,
        relatedVendor: input.relatedVendor ?? existing.relatedVendor,
        status,
      },
    });
  }

  return db.deadline.create({
    data: {
      title: input.title,
      category: input.category,
      date: input.date,
      status,
      autoGenerated: true,
      sourceModule: input.sourceModule,
      sourceId: input.sourceId,
      documentId: input.documentId,
      relatedPersonId: input.relatedPersonId,
      relatedClientId: input.relatedClientId,
      relatedVendor: input.relatedVendor,
      notes: input.notes,
    },
  });
}

export async function removeAutoDeadline(sourceModule: string, sourceId: string, category?: string) {
  await db.deadline.deleteMany({
    where: { sourceModule, sourceId, autoGenerated: true, ...(category ? { category } : {}) },
  });
}

/** Recompute UPCOMING/DUE_SOON/OVERDUE for every non-final deadline. Cheap enough to call on page load. */
export async function refreshDeadlineStatuses() {
  const open = await db.deadline.findMany({
    where: { status: { notIn: ["COMPLETED", "CANCELLED"] } },
  });
  const now = Date.now();
  for (const d of open) {
    const days = (d.date.getTime() - now) / (1000 * 60 * 60 * 24);
    const status = days < 0 ? "OVERDUE" : days <= 14 ? "DUE_SOON" : "UPCOMING";
    if (status !== d.status) {
      await db.deadline.update({ where: { id: d.id }, data: { status } });
    }
  }
}
