import PDFDocument from "pdfkit";
import { formatDate, formatMoney } from "@/lib/format";

export interface InvoicePdfData {
  number: string;
  invoiceDate: Date;
  dueDate: Date | null;
  clientNameSnapshot: string | null;
  clientCompanySnapshot: string | null;
  clientEmailSnapshot: string | null;
  clientAddressSnapshot: string | null;
  clientTRNSnapshot: string | null;
  description: string | null;
  quantity: number;
  unitPrice: number;
  vat: number;
  total: number;
  currency: string;
  status: string;
  notes: string | null;
}

export async function renderInvoicePdf(inv: InvoicePdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#1c2c6b").text("STARFLARE", { continued: false });
    doc.fontSize(10).fillColor("#475569").text("Influencer marketing & creator campaigns");
    doc.moveDown(1.5);

    doc.fontSize(16).fillColor("#0f172a").text(`Invoice ${inv.number}`);
    doc.fontSize(10).fillColor("#475569");
    doc.text(`Invoice date: ${formatDate(inv.invoiceDate)}`);
    if (inv.dueDate) doc.text(`Due date: ${formatDate(inv.dueDate)}`);
    doc.text(`Status: ${inv.status}`);
    doc.moveDown();

    doc.fontSize(11).fillColor("#0f172a").text("Bill to:", { underline: true });
    doc.fontSize(10).fillColor("#334155");
    if (inv.clientNameSnapshot) doc.text(inv.clientNameSnapshot);
    if (inv.clientCompanySnapshot) doc.text(inv.clientCompanySnapshot);
    if (inv.clientAddressSnapshot) doc.text(inv.clientAddressSnapshot);
    if (inv.clientEmailSnapshot) doc.text(inv.clientEmailSnapshot);
    if (inv.clientTRNSnapshot) doc.text(`TRN: ${inv.clientTRNSnapshot}`);
    doc.moveDown();

    const tableTop = doc.y + 10;
    doc.fontSize(10).fillColor("#ffffff");
    doc.rect(50, tableTop, 495, 20).fill("#1c2c6b");
    doc.fillColor("#ffffff").text("Description", 58, tableTop + 5, { width: 220 });
    doc.text("Qty", 280, tableTop + 5, { width: 40, align: "right" });
    doc.text("Unit price", 320, tableTop + 5, { width: 90, align: "right" });
    doc.text("Total", 420, tableTop + 5, { width: 115, align: "right" });

    const rowY = tableTop + 25;
    doc.fillColor("#0f172a").fontSize(10);
    doc.text(inv.description || "Services rendered", 58, rowY, { width: 220 });
    doc.text(String(inv.quantity), 280, rowY, { width: 40, align: "right" });
    doc.text(formatMoney(inv.unitPrice, inv.currency), 320, rowY, { width: 90, align: "right" });
    doc.text(formatMoney(inv.quantity * inv.unitPrice, inv.currency), 420, rowY, { width: 115, align: "right" });

    let y = rowY + 35;
    doc.moveTo(320, y).lineTo(545, y).strokeColor("#e2e8f0").stroke();
    y += 8;
    doc.text("Subtotal", 320, y, { width: 90, align: "right" });
    doc.text(formatMoney(inv.quantity * inv.unitPrice, inv.currency), 420, y, { width: 115, align: "right" });
    y += 18;
    doc.text("VAT", 320, y, { width: 90, align: "right" });
    doc.text(formatMoney(inv.vat, inv.currency), 420, y, { width: 115, align: "right" });
    y += 22;
    doc.fontSize(12).fillColor("#1c2c6b").text("Total", 320, y, { width: 90, align: "right" });
    doc.text(formatMoney(inv.total, inv.currency), 420, y, { width: 115, align: "right" });

    if (inv.notes) {
      doc.moveDown(3);
      doc.fontSize(9).fillColor("#64748b").text(`Notes: ${inv.notes}`);
    }

    doc.moveDown(3);
    doc.fontSize(8).fillColor("#94a3b8").text("Generated by Starflare ERP", 50, 760, { align: "center", width: 495 });

    doc.end();
  });
}
