-- CreateTable
CREATE TABLE "Counter" (
    "id" TEXT NOT NULL,
    "value" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "Counter_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Document" (
    "id" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "storedPath" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "checksum" TEXT NOT NULL,
    "documentType" TEXT NOT NULL,
    "category" TEXT,
    "tags" TEXT,
    "ocrStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "ocrText" TEXT,
    "ocrConfidence" DOUBLE PRECISION,
    "extractedFields" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "expiryDate" TIMESTAMP(3),
    "personId" TEXT,
    "clientId" TEXT,
    "invoiceId" TEXT,
    "receivedInvoiceId" TEXT,
    "bankTransactionId" TEXT,
    "bankStatementId" TEXT,
    "taxRecordId" TEXT,
    "rentRecordId" TEXT,
    "receivedContractId" TEXT,
    "sentContractId" TEXT,
    "policyId" TEXT,
    "expenseId" TEXT,
    "reimbursementId" TEXT,
    "compensationPaymentId" TEXT,
    "paymentId" TEXT,
    "ledgerEntryId" TEXT,
    "uploadedByType" TEXT,
    "uploadedByLabel" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Document_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Deadline" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'UPCOMING',
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "sourceModule" TEXT,
    "sourceId" TEXT,
    "documentId" TEXT,
    "relatedPersonId" TEXT,
    "relatedClientId" TEXT,
    "relatedVendor" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Deadline_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "recordType" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "previousValue" TEXT,
    "newValue" TEXT,
    "performedByType" TEXT,
    "performedByLabel" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Expense" (
    "id" TEXT NOT NULL,
    "actorType" TEXT NOT NULL,
    "actorLabel" TEXT NOT NULL,
    "personId" TEXT,
    "vendor" TEXT,
    "expenseDate" TIMESTAMP(3),
    "referenceDate" TIMESTAMP(3),
    "amount" DOUBLE PRECISION,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "vat" DOUBLE PRECISION,
    "taxRegNumber" TEXT,
    "paymentMethod" TEXT,
    "receiptNumber" TEXT,
    "description" TEXT,
    "category" TEXT,
    "reimbursable" BOOLEAN NOT NULL DEFAULT false,
    "reimbursePersonId" TEXT,
    "reimburseAmount" DOUBLE PRECISION,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "notes" TEXT,
    "documentId" TEXT,
    "clientId" TEXT,
    "campaignRef" TEXT,
    "receivedInvoiceId" TEXT,
    "contractType" TEXT,
    "contractId" TEXT,
    "bankTransactionId" TEXT,
    "ledgerEntryId" TEXT,
    "duplicateOfId" TEXT,
    "possibleDuplicate" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Invoice" (
    "id" TEXT NOT NULL,
    "number" TEXT NOT NULL,
    "clientId" TEXT,
    "clientNameSnapshot" TEXT,
    "clientCompanySnapshot" TEXT,
    "clientEmailSnapshot" TEXT,
    "clientAddressSnapshot" TEXT,
    "clientTRNSnapshot" TEXT,
    "invoiceDate" TIMESTAMP(3) NOT NULL,
    "dueDate" TIMESTAMP(3),
    "description" TEXT,
    "purchaseId" TEXT,
    "quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "unitPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "vat" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "total" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "paymentMethod" TEXT,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "receiptDocumentId" TEXT,
    "notes" TEXT,
    "contractType" TEXT,
    "contractId" TEXT,
    "source" TEXT NOT NULL DEFAULT 'MANUAL',
    "sourceStripeDocumentId" TEXT,
    "ledgerEntryId" TEXT,
    "sentAt" TIMESTAMP(3),
    "sentToEmail" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Client" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "companyName" TEXT,
    "tradeLicenseNumber" TEXT,
    "trn" TEXT,
    "mainContact" TEXT,
    "mainEmail" TEXT,
    "billingEmail" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "website" TEXT,
    "status" TEXT NOT NULL DEFAULT 'LEAD',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Client_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Purchase" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "paymentMethod" TEXT,
    "invoiceId" TEXT,
    "contractType" TEXT,
    "contractId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Purchase_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Subscription" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "packageName" TEXT NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3),
    "renewalDate" TIMESTAMP(3),
    "price" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Subscription_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Payment" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "date" TIMESTAMP(3) NOT NULL,
    "method" TEXT,
    "payer" TEXT,
    "payee" TEXT,
    "invoiceId" TEXT,
    "receivedInvoiceId" TEXT,
    "clientId" TEXT,
    "vendorName" TEXT,
    "personId" TEXT,
    "compensationPaymentId" TEXT,
    "reimbursementId" TEXT,
    "expenseId" TEXT,
    "proofDocumentId" TEXT,
    "bankTransactionId" TEXT,
    "stripeTransactionRef" TEXT,
    "reconciliation" TEXT NOT NULL DEFAULT 'UNMATCHED',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Payment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReceivedInvoice" (
    "id" TEXT NOT NULL,
    "vendorName" TEXT,
    "vendorCategory" TEXT,
    "invoiceNumber" TEXT,
    "invoiceDate" TIMESTAMP(3),
    "dueDate" TIMESTAMP(3),
    "amount" DOUBLE PRECISION,
    "vat" DOUBLE PRECISION,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "description" TEXT,
    "expenseCategory" TEXT,
    "taxRegNumber" TEXT,
    "paymentStatus" TEXT NOT NULL DEFAULT 'RECEIVED',
    "receiptDocumentId" TEXT,
    "documentId" TEXT,
    "bankTransactionId" TEXT,
    "ledgerEntryId" TEXT,
    "contractType" TEXT,
    "contractId" TEXT,
    "recurring" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ReceivedInvoice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BankStatement" (
    "id" TEXT NOT NULL,
    "bankName" TEXT,
    "accountName" TEXT,
    "iban" TEXT,
    "periodStart" TIMESTAMP(3),
    "periodEnd" TIMESTAMP(3),
    "openingBalance" DOUBLE PRECISION,
    "closingBalance" DOUBLE PRECISION,
    "documentId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BankStatement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BankTransaction" (
    "id" TEXT NOT NULL,
    "bankStatementId" TEXT,
    "date" TIMESTAMP(3) NOT NULL,
    "description" TEXT,
    "moneyIn" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "moneyOut" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "balanceAfter" DOUBLE PRECISION,
    "category" TEXT,
    "reconciliation" TEXT NOT NULL DEFAULT 'UNMATCHED',
    "linkedInvoiceId" TEXT,
    "linkedReceivedInvoiceId" TEXT,
    "linkedPersonId" TEXT,
    "linkedReimbursementId" TEXT,
    "linkedExpenseId" TEXT,
    "linkedLedgerEntryId" TEXT,
    "linkedContractType" TEXT,
    "linkedContractId" TEXT,
    "linkedTaxRecordId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BankTransaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BankDocument" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "documentId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BankDocument_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LedgerEntry" (
    "id" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "type" TEXT NOT NULL,
    "category" TEXT,
    "amount" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "clientId" TEXT,
    "vendorName" TEXT,
    "personId" TEXT,
    "paymentMethod" TEXT,
    "vat" DOUBLE PRECISION,
    "sourceDocumentId" TEXT,
    "invoiceId" TEXT,
    "bankTransactionId" TEXT,
    "sourceModule" TEXT,
    "sourceId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LedgerEntry_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Person" (
    "id" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT,
    "role" TEXT,
    "type" TEXT NOT NULL,
    "dateAdded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "contractStart" TIMESTAMP(3),
    "contractEnd" TIMESTAMP(3),
    "endReason" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "visaPermitDate" TIMESTAMP(3),
    "compensationAmount" DOUBLE PRECISION,
    "compensationCurrency" TEXT NOT NULL DEFAULT 'AED',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Person_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CompensationPayment" (
    "id" TEXT NOT NULL,
    "personId" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "referencePeriod" TEXT,
    "paymentDate" TIMESTAMP(3),
    "paymentMethod" TEXT,
    "status" TEXT NOT NULL DEFAULT 'DUE',
    "receiptDocumentId" TEXT,
    "signedReceiptDocumentId" TEXT,
    "ledgerEntryId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CompensationPayment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Reimbursement" (
    "id" TEXT NOT NULL,
    "personId" TEXT NOT NULL,
    "expenseId" TEXT,
    "documentId" TEXT,
    "amount" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "category" TEXT,
    "expenseDate" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'SUBMITTED',
    "ledgerEntryId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Reimbursement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TaxRecord" (
    "id" TEXT NOT NULL,
    "docType" TEXT NOT NULL,
    "taxRefNumber" TEXT,
    "authority" TEXT,
    "submissionDate" TIMESTAMP(3),
    "fiscalPeriod" TEXT,
    "issueDate" TIMESTAMP(3),
    "nextDueDate" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "documentId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TaxRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RentRecord" (
    "id" TEXT NOT NULL,
    "landlordName" TEXT,
    "location" TEXT,
    "officeName" TEXT,
    "startDate" TIMESTAMP(3),
    "endDate" TIMESTAMP(3),
    "monthlyRent" DOUBLE PRECISION,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "paymentSchedule" TEXT,
    "deposit" DOUBLE PRECISION,
    "noticePeriod" TEXT,
    "renewalDate" TIMESTAMP(3),
    "contractDocumentId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RentRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReceivedContract" (
    "id" TEXT NOT NULL,
    "counterpartyName" TEXT,
    "contractType" TEXT,
    "signatureDate" TIMESTAMP(3),
    "startDate" TIMESTAMP(3),
    "endDate" TIMESTAMP(3),
    "renewalDate" TIMESTAMP(3),
    "noticePeriod" TEXT,
    "contractValue" DOUBLE PRECISION,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "mainObligations" TEXT,
    "documentId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ReceivedContract_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SentContract" (
    "id" TEXT NOT NULL,
    "clientId" TEXT,
    "partnerName" TEXT,
    "contractType" TEXT,
    "packageName" TEXT,
    "price" DOUBLE PRECISION,
    "currency" TEXT NOT NULL DEFAULT 'AED',
    "duration" TEXT,
    "paymentTerms" TEXT,
    "signatureDate" TIMESTAMP(3),
    "startDate" TIMESTAMP(3),
    "endDate" TIMESTAMP(3),
    "renewalDate" TIMESTAMP(3),
    "documentId" TEXT,
    "invoiceId" TEXT,
    "subscriptionId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SentContract_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlatformPolicy" (
    "id" TEXT NOT NULL,
    "policyName" TEXT NOT NULL,
    "versionNumber" TEXT,
    "approvalDate" TIMESTAMP(3),
    "effectiveDate" TIMESTAMP(3),
    "reviewDate" TIMESTAMP(3),
    "documentId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlatformPolicy_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PolicyVersion" (
    "id" TEXT NOT NULL,
    "policyId" TEXT NOT NULL,
    "versionNumber" TEXT NOT NULL,
    "documentId" TEXT,
    "changeNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PolicyVersion_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Document_documentType_idx" ON "Document"("documentType");

-- CreateIndex
CREATE INDEX "Document_status_idx" ON "Document"("status");

-- CreateIndex
CREATE INDEX "Document_checksum_idx" ON "Document"("checksum");

-- CreateIndex
CREATE INDEX "Deadline_date_idx" ON "Deadline"("date");

-- CreateIndex
CREATE INDEX "Deadline_status_idx" ON "Deadline"("status");

-- CreateIndex
CREATE INDEX "Deadline_sourceModule_sourceId_idx" ON "Deadline"("sourceModule", "sourceId");

-- CreateIndex
CREATE INDEX "AuditLog_section_idx" ON "AuditLog"("section");

-- CreateIndex
CREATE INDEX "AuditLog_recordType_recordId_idx" ON "AuditLog"("recordType", "recordId");

-- CreateIndex
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- CreateIndex
CREATE INDEX "Expense_status_idx" ON "Expense"("status");

-- CreateIndex
CREATE INDEX "Expense_vendor_idx" ON "Expense"("vendor");

-- CreateIndex
CREATE INDEX "Expense_expenseDate_idx" ON "Expense"("expenseDate");

-- CreateIndex
CREATE UNIQUE INDEX "Invoice_number_key" ON "Invoice"("number");

-- CreateIndex
CREATE INDEX "Invoice_status_idx" ON "Invoice"("status");

-- CreateIndex
CREATE INDEX "Invoice_clientId_idx" ON "Invoice"("clientId");

-- CreateIndex
CREATE INDEX "Invoice_dueDate_idx" ON "Invoice"("dueDate");

-- CreateIndex
CREATE INDEX "Client_status_idx" ON "Client"("status");

-- CreateIndex
CREATE INDEX "Client_name_idx" ON "Client"("name");

-- CreateIndex
CREATE INDEX "Purchase_clientId_idx" ON "Purchase"("clientId");

-- CreateIndex
CREATE INDEX "Subscription_clientId_idx" ON "Subscription"("clientId");

-- CreateIndex
CREATE INDEX "Subscription_status_idx" ON "Subscription"("status");

-- CreateIndex
CREATE INDEX "Payment_type_idx" ON "Payment"("type");

-- CreateIndex
CREATE INDEX "Payment_reconciliation_idx" ON "Payment"("reconciliation");

-- CreateIndex
CREATE INDEX "Payment_date_idx" ON "Payment"("date");

-- CreateIndex
CREATE INDEX "ReceivedInvoice_paymentStatus_idx" ON "ReceivedInvoice"("paymentStatus");

-- CreateIndex
CREATE INDEX "ReceivedInvoice_dueDate_idx" ON "ReceivedInvoice"("dueDate");

-- CreateIndex
CREATE INDEX "BankTransaction_reconciliation_idx" ON "BankTransaction"("reconciliation");

-- CreateIndex
CREATE INDEX "BankTransaction_date_idx" ON "BankTransaction"("date");

-- CreateIndex
CREATE INDEX "LedgerEntry_date_idx" ON "LedgerEntry"("date");

-- CreateIndex
CREATE INDEX "LedgerEntry_type_idx" ON "LedgerEntry"("type");

-- CreateIndex
CREATE INDEX "LedgerEntry_category_idx" ON "LedgerEntry"("category");

-- CreateIndex
CREATE INDEX "Person_status_idx" ON "Person"("status");

-- CreateIndex
CREATE INDEX "Person_type_idx" ON "Person"("type");

-- CreateIndex
CREATE INDEX "CompensationPayment_personId_idx" ON "CompensationPayment"("personId");

-- CreateIndex
CREATE INDEX "CompensationPayment_status_idx" ON "CompensationPayment"("status");

-- CreateIndex
CREATE INDEX "Reimbursement_personId_idx" ON "Reimbursement"("personId");

-- CreateIndex
CREATE INDEX "Reimbursement_status_idx" ON "Reimbursement"("status");

-- CreateIndex
CREATE INDEX "TaxRecord_status_idx" ON "TaxRecord"("status");

-- CreateIndex
CREATE INDEX "TaxRecord_nextDueDate_idx" ON "TaxRecord"("nextDueDate");

-- CreateIndex
CREATE INDEX "PolicyVersion_policyId_idx" ON "PolicyVersion"("policyId");
