"use server";

import { db } from "@/lib/db";
import { computeDeadlineStatus } from "@/lib/deadlines";
import { logAudit } from "@/lib/audit";
import { parseFormDate } from "@/lib/format";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";

function str(fd: FormData, key: string): string | undefined {
  const v = fd.get(key);
  return typeof v === "string" && v.trim() ? v.trim() : undefined;
}

export async function createManualDeadline(formData: FormData) {
  const date = parseFormDate(formData.get("date")) ?? new Date();
  const deadline = await db.deadline.create({
    data: {
      title: str(formData, "title") ?? "Untitled deadline",
      category: str(formData, "category") ?? "Other",
      date,
      status: computeDeadlineStatus(date),
      autoGenerated: false,
      notes: str(formData, "notes"),
      relatedVendor: str(formData, "relatedVendor"),
    },
  });

  await logAudit({
    action: "created",
    section: "Deadlines",
    recordType: "Deadline",
    recordId: deadline.id,
    summary: `Added manual deadline: ${deadline.title}`,
    performedByType: "OSCAR",
    performedByLabel: "Oscar",
  });

  revalidatePath("/deadlines");
  redirect("/deadlines");
}

export async function updateDeadlineStatus(id: string, status: string) {
  await db.deadline.update({ where: { id }, data: { status } });
  revalidatePath("/deadlines");
}
