export const dynamic = "force-dynamic";

import { db } from "@/lib/db";
import { SubmitButton } from "@/components/SubmitButton";
import { PageHeader } from "@/components/ui/Page";
import { DataTable } from "@/components/ui/Table";
import { StatusBadge } from "@/components/ui/Badge";
import { Select } from "@/components/ui/Field";
import { formatDate } from "@/lib/format";
import { DEADLINE_STATUSES, labelize } from "@/lib/constants";
import { refreshDeadlineStatuses } from "@/lib/deadlines";
import { deadlineSourceUrl } from "@/lib/deadline-links";
import Link from "next/link";
import { updateDeadlineStatus } from "./actions";

const VIEWS = [
  { key: "all", label: "All" },
  { key: "today", label: "Today" },
  { key: "week", label: "This week" },
  { key: "month", label: "This month" },
  { key: "overdue", label: "Overdue" },
  { key: "critical", label: "Critical (overdue or ≤3 days)" },
];

export default async function DeadlinesPage({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  await refreshDeadlineStatuses();
  const { view = "all" } = await searchParams;

  const now = new Date();
  const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const endOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59, 59);
  const endOfWeek = new Date(startOfToday);
  endOfWeek.setDate(endOfWeek.getDate() + (7 - endOfWeek.getDay()));
  const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);
  const threeDaysOut = new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000);

  let where: any = { status: { not: "CANCELLED" } };
  if (view === "today") where = { ...where, date: { gte: startOfToday, lte: endOfToday } };
  else if (view === "week") where = { ...where, date: { gte: startOfToday, lte: endOfWeek } };
  else if (view === "month") where = { ...where, date: { gte: startOfToday, lte: endOfMonth } };
  else if (view === "overdue") where = { ...where, status: "OVERDUE" };
  else if (view === "critical") where = { ...where, OR: [{ status: "OVERDUE" }, { date: { lte: threeDaysOut } }] };

  const deadlines = await db.deadline.findMany({ where, orderBy: { date: "asc" } });

  return (
    <div>
      <PageHeader
        title="Deadline Calendar"
        description="Every important date across the ERP — invoices, contracts, HR, tax, rent, licenses — collected automatically."
        actions={<Link href="/deadlines/new" className="btn-primary">+ Add deadline</Link>}
      />
      <div className="flex flex-wrap gap-2 mb-4">
        {VIEWS.map((v) => (
          <Link key={v.key} href={`/deadlines?view=${v.key}`} className={view === v.key ? "btn-primary !py-1 !text-xs" : "btn-secondary !py-1 !text-xs"}>
            {v.label}
          </Link>
        ))}
      </div>
      <DataTable
        rows={deadlines}
        emptyMessage="No deadlines in this view."
        columns={[
          { header: "Title", render: (d) => {
            const url = deadlineSourceUrl(d.sourceModule, d.sourceId);
            return url ? <Link href={url} className="text-brand-700 hover:underline font-medium">{d.title}</Link> : d.title;
          } },
          { header: "Category", render: (d) => d.category },
          { header: "Date", render: (d) => formatDate(d.date) },
          { header: "Auto?", render: (d) => (d.autoGenerated ? "Auto" : "Manual") },
          {
            header: "Status",
            render: (d) => (
              <form
                action={async (fd: FormData) => {
                  "use server";
                  await updateDeadlineStatus(d.id, fd.get("status") as string);
                }}
                className="flex items-center gap-1.5"
              >
                <StatusBadge status={d.status} />
                <Select name="status" options={DEADLINE_STATUSES.map((s) => ({ value: s, label: labelize(s) }))} defaultValue={d.status} className="!py-1 !text-xs w-36" />
                <SubmitButton className="btn-ghost !py-1 !text-xs">Save</SubmitButton>
              </form>
            ),
          },
        ]}
      />
    </div>
  );
}
